title: Honeywell Maxpro Cloud
description: > # this means to ignore newlines until "baseurl:"
  Honeywell MAXPRO Cloud International.
permalink: ':title/'
baseurl: "/testhos" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Maxprocloud # add your name
author-img: Maxprocloud.jpg # add your photo
about-author: Designed for small-to-medium-sized (SMB) businesses, MAXPRO Cloud improves customer performance, ensures efficient safety and security, minimizes loss of inventory in retail environments, reduces IT infrastructure costs, and streamlines operations by empowering owners to make informed, real-time decisions – at any time, from anywhere. # add description
twitter: maxprocloud
facebook: maxprocloud
github: maxprocloud
linkedin: maxprocloud
email: manjunathkalburgi@gmail.com  

# Disqus
discus-identifier: maxprocloud # add your discus identifier

# Tracker
analytics: UA-113085000-1

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
